### START SECRETS
secrets:
  - &orm_log_db_pool_mysql root:root@tcp(localhost:23306)/memove_log_test
  - &orm_default_mysql root:root@tcp(localhost:23306)/memove_test
  - &orm_default_redis localhost:26379:11
  - &orm_variables_redis localhost:26379:12
  - &orm_default_rabbitmq_server amqp://rabbitmq_user:rabbitmq_password@localhost:25672/test

### END SECRETS

orm:
  log_db_pool:
    mysql: *orm_log_db_pool_mysql
  default:
    mysql: *orm_default_mysql
    redis: *orm_default_redis
    locker: default
    local_cache: 1000
    rabbitmq:
      server: *orm_default_rabbitmq_server
      queues:
        - name: msg.mail
        - name: msg.video_views
          prefetchCount: 1000
        - name: msg.track_consent_event
    dirty_queues:
      orm.es_index_VideoEntity: 1000
      orm.es_index_ClassEntity: 1000
      orm.es_index_AttendanceEntity: 1000
      orm.es_index_ProductEntity: 1000
      orm.es_index_CityEntity: 1000
      orm.es_index_StreetEntity: 1000
      orm.upload_UploadEntity: 1
      orm.new_order_sync_OrderEntity: 1
      orm.new_order_sync_SubscriptionOrderEntity: 1
      orm.order_sync_OrderEntity: 1
  variables:
    redis: *orm_variables_redis

