### START SECRETS
secrets:
  - &orm_log_db_pool_mysql root:root@tcp(localhost:7000)/log
  - &orm_default_mysql root:root@tcp(localhost:7000)/default
  - &orm_default_redis localhost:7001:1
  - &orm_variables_redis localhost:7001:2
  - &orm_default_rabbitmq_server amqp://rabbitmq_user:rabbitmq_password@localhost:7002/test

### END SECRETS

orm:
  log_db_pool:
    mysql: *orm_log_db_pool_mysql
  default:
    mysql: *orm_default_mysql
    redis: *orm_default_redis
    rabbitmq:
      server: *orm_default_rabbitmq_server
    locker: default
    local_cache: 1000
  variables:
    redis: *orm_variables_redis
