// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"summer-solutions/graphql-test-server/pkg/dic"
	"summer-solutions/graphql-test-server/pkg/entity"
)

type CarBrand struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Car struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	BrandID uint64
}

func (c *Car) Brand(ctx context.Context) *CarBrand {
	ormEngine := dic.OrmEngineForContext(ctx)
	carBrandEtity := &entity.CarBrandEntity{}
	ormEngine.LoadByID(c.BrandID, carBrandEtity)
	return &CarBrand{ID: fmt.Sprintf("%d", carBrandEtity.ID), Name: carBrandEtity.Name}
}
