### START INFRA SECRETS
infra_secrets:
  - &session_cookie_redis host.docker.internal:26379:4
  - &smtp_host host.docker.internal
  - &smtp_port "21025"
  - &video_stream_host_for_playing "http://127.0.0.1:28081"
  - &video_stream_host_for_streaming "rtmp://127.0.0.1:21935"
  - &oss_access_key LTAI4G5PUE97v42U6PiZMeCf
  - &oss_access_secret iDuYicBjiWbnJcIAF1MHN8pcmoNi3C

app_secrets:
  - &login_token_secret 5ometh1ng#s3cr3t#
  - &login_refresh_token_secret M&8!a"}
  - &sentry_dns ""
  - &email_secret "9ONnCxcNCqps2JR2ObuB7iOf0LLk3SeD"
  - &password_secret "8WlixOnLAeK904AR5vXH97NXCLiPVn3A"
  - &braintree_merchant_id "bn9nfj5fs6snws8r"
  - &braintree_public_key "54g6jyd7kqfr48hp"
  - &braintree_private_key "c278b9af82dcc38c380d1a25afdd3608"
  - &smtp_user "427b77ec794e2561b181dc5042a326b9"
  - &smtp_pass "e0786239ea1d0883cc7eddb1a09272da"
### END INFRA SECRETS

server:
  https: false
  port: 8080
locales:
  languages:
    - en-US
session:
  cookie:
    secret: spring
    redis: *session_cookie_redis
login:
  login_token:
    secret: *login_token_secret
    expire: 3600
  refresh_token:
    secret: *login_refresh_token_secret
    expire: 86400
  login_locked_time: 3600
  login_redis_key: logged:in:user:jwt
  login_redis_locked_key: locked:user
  refresh_token_redis_key: refresh:token:user:jwt
  max_login_tries: 5
  single_session_support: false
cors:
  - http://localhost:2000
email_secret: *email_secret
password_secret: *password_secret
frontend: http://localhost:2000
backend: http://localhost:28080
smtp:
  host: *smtp_host
  user: "test@coretrix.com"
  pass: ""
  port: *smtp_port
  tls: false
  from: "noreply@memove.com"
contact_email: "contact@memove.com"
sentry:
  dns: *sentry_dns
braintree:
  merchant_id: *braintree_merchant_id
  public_key: *braintree_public_key
  private_key: *braintree_private_key
oss:
  host: oss-eu-central-1.aliyuncs.com
  access_key_id: *oss_access_key
  access_key_secret: *oss_access_secret
  buckets:
    memove-products-images: memove-products-images-local.oss-eu-central-1.aliyuncs.com
    memove-users-avatars: memove-users-avatars-local.oss-eu-central-1.aliyuncs.com
    memove-classes-videos: memove-classes-videos-local.oss-eu-central-1.aliyuncs.com
    memove-classes-videos-images: memove-classes-videos-images-local.oss-eu-central-1.aliyuncs.com
    memove-classes-videos-playlists: memove-classes-videos-playlists-local.oss-eu-central-1.aliyuncs.com
    memove-trainers-videos: memove-trainers-videos-local.oss-eu-central-1.aliyuncs.com
    memove-users-cover-images: memove-users-cover-images-local.oss-eu-central-1.aliyuncs.com
    memove-audio-tracks: memove-audio-tracks-local.oss-eu-central-1.aliyuncs.com
    memove-product-overview-sections-images: memove-product-overview-sections-images-local.oss-eu-central-1.aliyuncs.com
shared_dir: /tmp
video_stream_host_for_playing: *video_stream_host_for_playing
video_stream_host_for_streaming: *video_stream_host_for_streaming
captcha_url: "https://www.google.com/recaptcha/api/siteverify"
captcha_secret: "6LdLmNoZAAAAAFwhYDoQrxQIq1l5DFnu7uKR4FZ-"
nimble_client_id: "65d86905-e52a-43c4-8784-06ea47986b3e"
nimble_direct_host: ""
nimble_api_key: "1699696bdcb79c63f2d253766094aa53"
nimble_ppv_password: "cz55Ks7PN334q6tStDZ9xLPk3z54nvjN"
