// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Currently logged user
type User struct {
	ID string `json:"id"`
	// Unique user name
	Username string `json:"username"`
}

func (User) IsEntity() {}
